# CMake generated Testfile for 
# Source directory: /home/claude/repos/jlpicart/fw/tests
# Build directory: /home/claude/repos/jlpicart/fw/tests/host
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(smoke_test "/home/claude/repos/jlpicart/fw/tests/host/smoke_test")
set_tests_properties(smoke_test PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;124;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_diag "/home/claude/repos/jlpicart/fw/tests/host/test_diag")
set_tests_properties(test_diag PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;130;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_log "/home/claude/repos/jlpicart/fw/tests/host/test_log")
set_tests_properties(test_log PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;135;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_otp "/home/claude/repos/jlpicart/fw/tests/host/test_otp")
set_tests_properties(test_otp PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;140;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_security_posture "/home/claude/repos/jlpicart/fw/tests/host/test_security_posture")
set_tests_properties(test_security_posture PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;145;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_policy "/home/claude/repos/jlpicart/fw/tests/host/test_policy")
set_tests_properties(test_policy PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;150;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_capability_registry "/home/claude/repos/jlpicart/fw/tests/host/test_capability_registry")
set_tests_properties(test_capability_registry PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;159;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_api_window "/home/claude/repos/jlpicart/fw/tests/host/test_api_window")
set_tests_properties(test_api_window PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;170;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_network_service "/home/claude/repos/jlpicart/fw/tests/host/test_network_service")
set_tests_properties(test_network_service PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;197;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_menu_mailbox "/home/claude/repos/jlpicart/fw/tests/host/test_menu_mailbox")
set_tests_properties(test_menu_mailbox PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;224;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_menu_stub "/home/claude/repos/jlpicart/fw/tests/host/test_menu_stub")
set_tests_properties(test_menu_stub PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;233;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_storage "/home/claude/repos/jlpicart/fw/tests/host/test_storage")
set_tests_properties(test_storage PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;243;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_store "/home/claude/repos/jlpicart/fw/tests/host/test_store")
set_tests_properties(test_store PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;251;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_allocator "/home/claude/repos/jlpicart/fw/tests/host/test_allocator")
set_tests_properties(test_allocator PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;291;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_bus_mapper "/home/claude/repos/jlpicart/fw/tests/host/test_bus_mapper")
set_tests_properties(test_bus_mapper PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;319;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_collections "/home/claude/repos/jlpicart/fw/tests/host/test_collections")
set_tests_properties(test_collections PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;330;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_profiles "/home/claude/repos/jlpicart/fw/tests/host/test_profiles")
set_tests_properties(test_profiles PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;351;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_usb_scanner "/home/claude/repos/jlpicart/fw/tests/host/test_usb_scanner")
set_tests_properties(test_usb_scanner PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;381;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_menu_app "/home/claude/repos/jlpicart/fw/tests/host/test_menu_app")
set_tests_properties(test_menu_app PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;406;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_system_settings "/home/claude/repos/jlpicart/fw/tests/host/test_system_settings")
set_tests_properties(test_system_settings PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;437;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_core_service "/home/claude/repos/jlpicart/fw/tests/host/test_core_service")
set_tests_properties(test_core_service PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;467;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_save_store "/home/claude/repos/jlpicart/fw/tests/host/test_save_store")
set_tests_properties(test_save_store PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;484;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_boot_mode "/home/claude/repos/jlpicart/fw/tests/host/test_boot_mode")
set_tests_properties(test_boot_mode PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;511;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_stats_store "/home/claude/repos/jlpicart/fw/tests/host/test_stats_store")
set_tests_properties(test_stats_store PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;542;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_device_identity "/home/claude/repos/jlpicart/fw/tests/host/test_device_identity")
set_tests_properties(test_device_identity PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;569;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_smk "/home/claude/repos/jlpicart/fw/tests/host/test_smk")
set_tests_properties(test_smk PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;596;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_policy_enforcement "/home/claude/repos/jlpicart/fw/tests/host/test_policy_enforcement")
set_tests_properties(test_policy_enforcement PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;608;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_psg "/home/claude/repos/jlpicart/fw/tests/host/test_psg")
set_tests_properties(test_psg PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;644;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_opl4 "/home/claude/repos/jlpicart/fw/tests/host/test_opl4")
set_tests_properties(test_opl4 PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;653;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_sunrise_ide "/home/claude/repos/jlpicart/fw/tests/host/test_sunrise_ide")
set_tests_properties(test_sunrise_ide PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;659;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_scc "/home/claude/repos/jlpicart/fw/tests/host/test_scc")
set_tests_properties(test_scc PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;665;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_rom_loading "/home/claude/repos/jlpicart/fw/tests/host/test_rom_loading")
set_tests_properties(test_rom_loading PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;678;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_content_store "/home/claude/repos/jlpicart/fw/tests/host/test_content_store")
set_tests_properties(test_content_store PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;701;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_bundle_sig "/home/claude/repos/jlpicart/fw/tests/host/test_bundle_sig")
set_tests_properties(test_bundle_sig PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;724;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
add_test(test_device_check "/home/claude/repos/jlpicart/fw/tests/host/test_device_check")
set_tests_properties(test_device_check PROPERTIES  _BACKTRACE_TRIPLES "/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;118;add_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;736;add_host_test;/home/claude/repos/jlpicart/fw/tests/CMakeLists.txt;0;")
