// menu_stub_bin.h — embedded Z80 menu stub binary.
//
// This file is GENERATED by the build_menu_stub CMake target:
//   cmake --build build --target build_menu_stub
//
// Until SDCC is installed and the target has been run, this placeholder
// ships a zero-size stub so the firmware still compiles (bus wiring is
// unaffected; menu page will contain the header/mailbox but no Z80 code).
//
// To build the real stub:
//   bash fw/tools/get_sdcc.sh
//   cmake --build build --target build_menu_stub

#pragma once
#include <cstdint>

#pragma message("menu_stub_bin.h: placeholder stub — run: bash fw/tools/get_sdcc.sh && cmake --build build --target build_menu_stub")
static const uint8_t kMenuStubBin[] = { 0x00u };
static const uint16_t kMenuStubBin_SIZE = 0u;
