#!/usr/bin/env python3
"""bin_to_c_array.py — convert a binary file to a C uint8_t array header.

Usage:
    python3 bin_to_c_array.py <input.bin> <array_name> > output.h

If <input.bin> does not exist, emits a zero-size placeholder array with a
#warning so the firmware still compiles without SDCC installed.
"""

import sys
import os

def main():
    if len(sys.argv) < 3:
        print(f"usage: {sys.argv[0]} <input.bin> <array_name>", file=sys.stderr)
        sys.exit(1)

    path = sys.argv[1]
    name = sys.argv[2]

    if not os.path.exists(path):
        print(f'#pragma message("SDCC not available — {name} is an empty placeholder")')
        print(f"static const uint8_t {name}[] = {{ 0x00u }};")
        print(f"static const uint16_t {name}_SIZE = 0u;")
        return

    with open(path, "rb") as f:
        data = f.read()

    if len(data) == 0:
        print(f'#pragma message("{name}: stub.bin is empty")')
        print(f"static const uint8_t {name}[] = {{ 0x00u }};")
        print(f"static const uint16_t {name}_SIZE = 0u;")
        return

    print(f"// Generated by bin_to_c_array.py — do not edit.")
    print(f"// Source: {os.path.basename(path)}  ({len(data)} bytes)")
    print(f"#pragma once")
    print(f"#include <cstdint>")
    print(f"// clang-format off")
    print(f"static const uint8_t {name}[] = {{")
    for i, b in enumerate(data):
        if i % 16 == 0:
            print("   ", end="")
        print(f" 0x{b:02x}u,", end="")
        if (i + 1) % 16 == 0:
            print()
    if len(data) % 16 != 0:
        print()
    print("};")
    print(f"// clang-format on")
    print(f"static const uint16_t {name}_SIZE = {len(data)}u;")

if __name__ == "__main__":
    main()
